### ISSUE TITLE
Add my portfolio

### ISSUE THREAD

**Issue by rajeshkumaryadavdotcom** [emmabostian/developer-portfolios#1203]
Hi there, would you be able to add two more from my side please in the list.

r-k-y.com (nextjs)
RajeshKumarYadav.com (Angular)

Thank you.
Raj

**Comment by eclectic-coding** [comment]
Yeh, just open a PR and I will merge into the site

**Comment by rajeshkumaryadavdotcom** [comment]
> Yeh, just open a PR and I will merge into the site

Will do thanks

**Comment by rajeshkumaryadavdotcom** [comment]
Sent the PR, please review and approve, thanks.

**Comment by rajeshkumaryadavdotcom** [comment]
Thank you, now I can see my portfolio listed.
