### ISSUE TITLE
Add Jehad Almaliki Portofilio

### ISSUE THREAD

**Issue by Jehadalmaliki** [emmabostian/developer-portfolios#1285]
This is my powerful portofilio I am so a proud  of it , I want to share with you .

**Comment by Jehadalmaliki** [comment]
https://jehadali.netlify.app/

**Comment by eclectic-coding** [comment]
Very nice. Please create a Pull Request and I will add. Refer to the CONTRIBUTING.md to get started.
Reach out with any questions
