### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by karthiknmenon** [emmabostian/developer-portfolios#135]
What are your views on creating a GitHub Pages for the makrdown file ?

**Comment by stevebaros** [comment]
Three possible ways to achieve this .
1.create [dev-portfolios.github.io](dev-portfolios.github.io)
2.Set up a freenom domain on a community server and link its CNAME via GH-pages

Any more thoughts ?

**Comment by jakeherp** [comment]
Closing this, see comments in #174 for reference.
