### ISSUE TITLE
Grouping portfolio

### ISSUE THREAD

**Issue by surapuramakhil** [emmabostian/developer-portfolios#1531]
group by name doesn't add any value - just helpfull to lookup if you already know name.

Suggestion is to Add addition info - like Frontend, Full-Stack, or other information at read me level. (or) grouping sites based on profile

**Comment by eclectic-coding** [comment]
Thank you for the suggestion.

However, for this stage of the development of this repo, any additional grouping would not be possible.

To gather the additional information is not easily possible for hundred of entries in a Markdown flat file, with no database.
