### ISSUE TITLE
open link in new tab

### ISSUE THREAD

**Issue by Abhijay007** [emmabostian/developer-portfolios#554]
Right now when someone clicks on the link the website get open in the same tab instead of the new tab which is making it a bit difficult to explore multiple portfolio sites at the same time, if the link gets open in a new tab then it will look good and help developers to explore multiples sites and allow them to switch between tabs easily !!

**Comment by nakshatrasinghh** [comment]
@emmabostian can I fix this issue?

**Comment by NhlanhlaHasane** [comment]
How do you propose to fix this? Please kindly share your thought process to fixing it?

**Comment by eclectic-coding** [comment]
The reason we do not provide this feature is to provide a more accessible experience. [W3C](https://www.w3.org/TR/WCAG20-TECHS/G200.html) provides guidelines for use cases when a redirect to a new page makes since, and this use case does not really fall into those criteria.
