### ISSUE TITLE
Portfolio classification

### ISSUE THREAD

**Issue by ogaston** [emmabostian/developer-portfolios#83]
**Hi Emma,**

I notice that the repo is turning large. Maybe a way to arrange all the portfolios might be classify them by topic. example:
- _Developers_
- _Designer_
etc...

What do you think about it?

Thank for your time.

**Comment by KumarAbhirup** [comment]
This sounds cool. Thoughts, @thblckjkr?

**Comment by thblckjkr** [comment]
@KumarAbhirup I love the idea, the only thing we should make sure first, is if @emmawedekind is ok with that.

Also, we should think on possible classifications.

**Comment by KumarAbhirup** [comment]
We will wait for @emmawedekind's feedback on this.

**Comment by jakeherp** [comment]
Closing, see #174
